{% set name = "apache-flink-libraries" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache-flink-libraries-{{ version }}.tar.gz
  sha256: 916cdd32d870db6cf6409f621b3c5baedfaf1ad4bb7b638c68af488475f27f46

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - pyflink
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://flink.apache.org
  summary: Apache Flink Libraries
  license: Apache-2.0 AND BSD-2-Clause AND MPL-2.0 AND Unlicense AND MIT AND BSD-3-Clause AND EPL-2.0
  license_file:
    - NOTICE
    - LICENSE
    - deps/licenses/LICENSE.base64
    - deps/licenses/LICENSE.py4j
    - deps/licenses/LICENSE.scala
    - deps/licenses/LICENSE.minlog
    - deps/licenses/LICENSE.jzlib
    - deps/licenses/LICENSE.google-auth-library-credentials
    - deps/licenses/LICENSE.influx
    - deps/licenses/LICENSE.antlr-java-grammar-files
    - deps/licenses/LICENSE.protobuf
    - deps/licenses/LICENSE.pyrolite
    - deps/licenses/LICENSE.jline
    - deps/licenses/LICENSE.kryo
    - deps/licenses/LICENSE.jsr166y
    - deps/licenses/LICENSE.jaxb
    - deps/licenses/LICENSE.javax.activation
    - deps/licenses/LICENSE.asm
    - deps/licenses/LICENSE.icu4j
    - deps/licenses/LICENSE.automaton
    - deps/licenses/LICENSE.grizzled-slf4j
    - deps/licenses/LICENSE.slf4j-api
    - deps/licenses/LICENSE.janino
    - deps/licenses/LICENSE.antlr-runtime
    - deps/licenses/LICENSE.webbit

extra:
  recipe-maintainers:
    - gforsyth
